version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.40.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    volumes:
      - ./infra/metrics/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - dev

  grafana:
    image: grafana/grafana:9.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./infra/metrics/grafana/data/:/var/lib/grafana
      - ./infra/metrics/grafana/config/:/etc/grafana
      - ./infra/metrics/grafana/dashboards/:/etc/grafana/provisioning/dashboards/
    networks:
      - dev

  normal_process:
    build:
      context: .
      dockerfile: ./dockerfiles/normal_process/Dockerfile
    networks:
      - dev
    volumes:
      - ./results:/tmp/goperformance/
    ports:
      - "8085:2112"

  goroutines_process:
    build:
      context: .
      dockerfile: ./dockerfiles/go_routines/Dockerfile
    networks:
      - dev
    volumes:
      - ./results:/tmp/goperformance/
    ports:
      - "8086:2112"

  channels_process:
    build:
      context: .
      dockerfile: ./dockerfiles/channels/Dockerfile
    networks:
      - dev
    volumes:
      - ./results:/tmp/gochannel/
    ports:
      - "8087:2112"


networks:
  dev:
    driver: bridge
