global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'normal_process'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['normal_process:2112']
  - job_name: 'goroutines_process'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'goroutines_process:2112' ]
  - job_name: 'channels_process'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'channels_process:2112' ]
